### ISSUE TITLE
TWRP Problem

### ISSUE THREAD

**Issue by h4rm00n** [mickaelmendes50/android_device_xiaomi_psyche#1]
After I used the fastboot version, it's not able to boot twrp via "fastboot boot twrp.img". But if I use recovery version,after "fastboot flash vendor_boot vendor_boot.img", I don't know how to reboot into recovery, "fastboot reboot recovery" has failed, and I can't reboot into system. I have also tried install twrp by skkk, using sideload mode, it also failed...
![IMG_2023-09-20-22-38-33-823](https://github.com/mickaelmendes50/android_device_xiaomi_psyche/assets/42669242/3318bc9b-265b-43dc-a906-fd868b5ef920)

**Comment by mickaelmendes50** [comment]
Hello! This isn't a bug, it's an expected behavior.

As you can see here, I use vendor_boot as recovery in PA:
https://github.com/mickaelmendes50/android_device_xiaomi_psyche/blob/topaz/BoardConfig.mk#L162

If you check the XDA Thread of the ROM, you'll notice the TWRP isn't mentioned on flashing instructions, as I can't ensure a recovery from a third party project to be working as I expect.

If you rally want to use TWRP, ask to a TWRP dev to build a vendor_boot TWRP with UNICODE / F2FS Compression support. This will make it be compatible with AOSPA.

I won't remove the filesystem features I'm using only to keep a "support" to a custom recovery if a third party project.
